
easy_admin:
  site_name: 'MemePostBot'
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
  entities:
    User:
      class: App\Entity\MemeUser


    Meme:
      class: App\Entity\Meme
      list:
        fields:
          - {property: 'image', type: 'image', base_path: '%app.path.meme_images%'}
      show:
        fields:
          - {property: 'image', type: 'image', base_path: '%app.path.meme_images%'}
      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'caption', type: 'textarea' }