vich_uploader:
    db_driver: orm

    mappings:
        meme_images:
            uri_prefix: '%app.path.meme_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.meme_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer